devtools::install_github("ohdsi/DatabaseConnector", dep = FALSE)
devtools::install_github("ohdsi/Cyclops", ref = "v2.0.0", dep = FALSE)
devtools::install_github("ohdsi/FeatureExtraction", ref = "v2.1.5", dep = FALSE)
devtools::install_github("ohdsi/ParallelLogger", dep = FALSE)
devtools::install_github("ohdsi/EmpiricalCalibration", dep = FALSE)
devtools::install_github("ohdsi/CohortMethod", dep = FALSE)
devtools::install_github("ohdsi/SelfControlledCaseSeries", ref = "develop", dep = F)
devtools::install_github("ohdsi/CaseControl", ref = "develop", dep = F)
devtools::install_github("ohdsi/SelfControlledCohort", ref = "develop", dep = F)
devtools::install_github("ohdsi/CaseCrossover", ref = "develop", dep = F)
devtools::install_github("ohdsi/MethodEvaluation", ref = "develop", dep = FALSE)
